name: Auto approve v3
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.branch == 'qa'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
