name: Auto approve v55
on: pull_request_target

jobs:
  build:
    if: github.head_ref == 'qa'
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
